// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ-cldUy6QITYC1BwBtotTttXuGoQu61Q',
    appId: '1:582973375044:web:956d55eaea7a42ac2b3211',
    messagingSenderId: '582973375044',
    projectId: 'khujbokoi-562ec',
    authDomain: 'khujbokoi-562ec.firebaseapp.com',
    storageBucket: 'khujbokoi-562ec.firebasestorage.app',
    measurementId: 'G-NCGX7LGTKE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiyyQfgz9aHSgkPhI4fGEUhKwbE1B5wEc',
    appId: '1:582973375044:android:3856e000bfc37f7e2b3211',
    messagingSenderId: '582973375044',
    projectId: 'khujbokoi-562ec',
    storageBucket: 'khujbokoi-562ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU_YkKciEZtdzTCJ-7jQxf7mIpsvrPviY',
    appId: '1:582973375044:ios:a06dc954d49c967d2b3211',
    messagingSenderId: '582973375044',
    projectId: 'khujbokoi-562ec',
    storageBucket: 'khujbokoi-562ec.firebasestorage.app',
    iosBundleId: 'com.khujbokoi.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU_YkKciEZtdzTCJ-7jQxf7mIpsvrPviY',
    appId: '1:582973375044:ios:a06dc954d49c967d2b3211',
    messagingSenderId: '582973375044',
    projectId: 'khujbokoi-562ec',
    storageBucket: 'khujbokoi-562ec.firebasestorage.app',
    iosBundleId: 'com.khujbokoi.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ-cldUy6QITYC1BwBtotTttXuGoQu61Q',
    appId: '1:582973375044:web:b4073dba04efa1a72b3211',
    messagingSenderId: '582973375044',
    projectId: 'khujbokoi-562ec',
    authDomain: 'khujbokoi-562ec.firebaseapp.com',
    storageBucket: 'khujbokoi-562ec.firebasestorage.app',
    measurementId: 'G-XG7BEP2R1H',
  );
}
